### ISSUE TITLE
Ayuda en línea de código

### ISSUE THREAD

**Issue by yurbaez** [maestria-geotel-201902/unidad-1-asignacion-2-rasters-y-exportar-datos-espaciales-yurbaez#1]
@geofis Hola profesor!!

Como no pude ir a clases el martes por problemas de salud y revisando los correos que ud envío, tenía pendiente esta asignación, ayer temprano inicié pero no he podido avanzar en este mandato, no logro visualizar que debo colocar donde dice **drive**, estuve consultando en la web, incluso hasta compañeros que si pudieron asistir a clases, pero me ha sido imposible.

Este es parte del mandato:

Usando la función `st_write`, exporta el objeto `miprov` como GeoPackage a la carpeta `data` con el nombre `miprovexportado.gpkg`

```{r}
st_layers('data/divisionRD.gpkg')
prov <- st_read(dsn = 'data/divisionRD.gpkg', layer = 'PROVCenso2010')
miprov <- prov[prov$PROV %in% '21', ]
st_write(obj = miprov, dsn = 'data/divisionRD.gpkg', driver = '...')

atenta a su respuesta!

**Comment by geofis** [comment]
Que haya salud.

En realidad, no envié dicha asignación, pero si te adelantas, perfecto. Si te fijas en el material de apoyo, sección [Exportar datos](https://github.com/maestria-geotel-master/material-de-apoyo/blob/master/ref/introduccion-a-r.md#exportar-datos), verás que la función `st_drivers()` devuelve los drives disponibles. Verás que los GeoPackage usan el driver que lleva por nombre `GPKG`.

**Comment by yurbaez** [comment]
@geofis 

opppsss, es que dentro del repositorio de las asignaciones está al final y fecha límite. Pues muchas gracias, leeré la sección sugerida.

Gracias!!!
