### ISSUE TITLE
Error en tejido R markdown

### ISSUE THREAD

**Issue by yurbaez** [maestria-geotel-201902/unidad-1-asignacion-2-rasters-y-exportar-datos-espaciales-yurbaez#2]
@geofis 

![image](https://user-images.githubusercontent.com/39610484/68303924-30ec6e80-007b-11ea-9ed0-05394641fc10.png)

Quitting from lines 79-85 (README.Rmd) 
Error in CPL_write_ogr(obj, dsn, layer, driver, as.character(dataset_options),  : 
  Dataset already exists.
Calls: <Anonymous> ... eval -> eval -> st_write -> st_write.sf -> CPL_write_ogr
Execution halted

**Comment by geofis** [comment]
@yurbaez El error avisa `Dataset already exists`, es decir, el objeto (seguramente `miprovexportado.gpkg`) ya existe. Bórralo primero (me parece que de la carpeta `data`), y luego teje. Visita [este *issue*](https://github.com/maestria-geotel-201902/unidad-1-asignacion-2-rasters-y-exportar-datos-espaciales-MirelSIG/issues/1), que lo explico en detalle.

**Comment by yurbaez** [comment]
@geofis 

Listo!! Gracias.

Corregido.
